Reto 2
pedrovelasquez9/retos-de-programacion pull request #14
Opened 2023-02-03 14:42 UTC by Darik15ing

Ajuste comentarios

2023-02-03 14:43 UTC, Darik15ing commented
Ajuste comentarios

2023-02-03 18:48 UTC, pedrovelasquez9 requested changes
Para mantener el estándar sugerido, cambiemos los nombres de funciones y variables a inglés

2023-02-05 19:01 UTC, Darik15ing commented
Traducciones solicitadas realizadas

2023-02-08 12:34 UTC, pedrovelasquez9 approved these changes

2023-02-08 12:34 UTC, merged